import pandas as pd
import matplotlib.pyplot as plt

def plot_telemetry():
    try:
        # Load the data generated by C++
        df = pd.read_csv('../build/telemetry.csv')
    except FileNotFoundError:
        print("Error: telemetry.csv not found. Did you run the C++ program?")
        return

    plt.figure(figsize=(10, 6))

    # Plot Target vs Actual Altitude
    plt.subplot(2, 1, 1)
    plt.plot(df['Time'], df['Target'], 'r--', label='Target Altitude')
    plt.plot(df['Time'], df['Actual'], 'b-', label='Actual Altitude (Sensor)')
    plt.title('Flight Telemetry: Altitude Control')
    plt.ylabel('Meters')
    plt.legend()
    plt.grid(True)

    # Plot Motor Output (to see how hard the PID is working)
    plt.subplot(2, 1, 2)
    plt.fill_between(df['Time'], df['Output'], color='green', alpha=0.3, label='Motor Power')
    plt.ylabel('Power Output')
    plt.xlabel('Time (seconds)')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    plot_telemetry()